name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container: openjdk
    steps:
      - uses: actions/checkout@v2
      - name: Build Project
        run: |
          pwd
          ls
          java -version
          javac -version
          javac Projects/P3/src/*.java
          
          javac -cp "Projects/P3/src/" Projects/P3/src/*.java
          
          javac -cp "tests/junit-4.10.jar:Projects/P3/src/:Projects/P3/tests/" Projects/P3/src/*.java Projects/P3/tests/*.java